hw1.out:hw1.o TwoDimensional.o ThreeDimensional.o
	g++ -Wall hw1.o TwoDimensional.o ThreeDimensional.o -o hw1.out 

TwoDimensional.o: TwoDimensional.cpp TwoDimensional.h
	g++ -Wall -c TwoDimensional.cpp

ThreeDimensional.o: ThreeDimensional.cpp ThreeDimensional.h
	g++ -Wall -c ThreeDimensional.cpp
