Proj2: Proj2.cpp Blackjack.cpp Card.cpp Deck.cpp Card.h Deck.h Player.h Hand.h
	g++ -ansi -Wall Proj2.cpp Blackjack.cpp Blackjack.h  Card.cpp Card.h Deck.cpp Deck.h Hand.h Player.h  -o Proj2.out





