Proj3.out: Proj3.o Proj3Aux.o Fraction.o 
	g++ Proj3.o Proj3Aux.o Fraction.o -o Proj3.out 
Proj3.o: Proj3.cpp
	g++ -Wall -c Proj3.cpp
Proj3Aux.o: Proj3Aux.cpp Proj3Aux.h
	g++ -Wall -c Proj3Aux.cpp
Fraction.o: Fraction.cpp Fraction.h 
	g++ -Wall -c Fraction.cpp 
