Proj2.out: Proj2.o Card.o Deck.o Player.o Hand.o Blackjack.o
	g++ Proj2.o Card.o Deck.o Player.o Hand.o Blackjack.o -o Proj2.out

Proj2.o:Proj2.cpp 
	g++ -Wall -c Proj2.cpp

Card.o:Card.cpp Card.h
	g++ -Wall -c Card.cpp

Deck.o:Deck.cpp Deck.h
	g++ -Wall -c Deck.cpp

Hand.o:Hand.cpp Hand.h
	g++ -Wall -c Hand.cpp

Player.o:Player.cpp Player.h
	g++ -Wall -c Player.cpp