# Makefile courtesy of Mr. Park 
# Source originally posted to Piazza
CPPFLAGS = -Wall
OBJS = Proj2.o Card.o Deck.o Player.o Hand.o Blackjack.o
Proj2.out: ${OBJS}
	g++ ${OBJS} -o Proj2.out

Card.o: Card.h
Deck.o: Deck.h
Hand.o: Hand.h
Player.o: Player.h
Blackjack.o: Blackjack.h