CPPFLAGS = -ansi -Wall -g

Proj5.out: Proj5.o Proj5Aux.o GridGame.o TicTacToe.o Reversi.o Life.o
	g++ Proj5.o Proj5Aux.o GridGame.o TicTacToe.o Reversi.o Life.o -lg -o Proj5.out

clean:
	rm -f Proj5.o Proj5Aux.o GridGame.o TicTacToe.o Reversi.o Life.o Proj5.out

