#include <iostream>
#include <string>
#include <fstream>
#include <stdio.h>
using namespace std;

int main(int argc, char* argv[]) {

  string text[] = {
    "--------------------- C Code ---------------------",
    "#include<string.h>",
    "#include<stdlib.h>",
    "#include<stdio.h>",
    "",
    "char *text [] = {",
    "};",
    "",
    "int main () {",
    "  char newline = 012, quote = 042, bslash = 0134, *p;",
    "  int i = 0, hstart = 42, hstop = 51;",
    "  int bstart = 51, bstop = 81, maxline = 183;",
    "  FILE *fout;",
    "",
    "  fout = fopen(\"cpcopy.cpp\", \"w\");",
    "  if (fout == NULL) {",
    "    fprintf(stderr, \"cannot open output file\");",
    "    return 0;",
    "  }",
    "",
    "  for (i = hstart; i < hstop; i++) {",
    "    fprintf (fout, \"%s%c\", text[i], newline);",
    "  }",
    "",
    "  for (i = 0; i < maxline; i++) {",
    "    fprintf (fout, \"    %c\", quote);",
    "    for (p = text[i]; *p; p++) {",
    "      if (*p == quote)",
    "        fprintf(fout, \"%c\", bslash);",
    "      fprintf(fout, \"%c\", *p);",
    "    }",
    "    fprintf (fout, \"%c,%c\", quote, newline);",
    "  }",
    "",
    "  for (i = bstart; i < bstop; i++) {",
    "    fprintf (fout, \"%s%c\", text[i], newline);",
    "  }",
    "",
    "  fclose(fout);",
    "  return 0;",
    "}",
    "-------------------- C++ Code --------------------",
    "#include <iostream>",
    "#include <string>",
    "#include <fstream>",
    "#include <stdio.h>",
    "using namespace std;",
    "",
    "int main(int argc, char* argv[]) {",
    "",
    "  string text[] = {",
    "  };",
    "",
    "  char quote = 042, bslash = 0134, nline = 012;",
    "  int i = 0, hstart = 82, hstop = 83;",
    "  int bstart = 83, bstop = 106, maxLine = 183;",
    "  const char* p;",
    "",
    "  ofstream outFile(\"pcopy.py\");",
    "",
    "  for (i = hstart; i < hstop; ++i) {",
    "    outFile << text[i] << nline;",
    "  }",
    "",
    "  for (i = 0; i < maxLine; ++i) {",
    "    outFile << \"    \" << quote;",
    "    for (p = text[i].c_str(); *p; ++p) {",
    "      if (*p == quote)",
    "        outFile << bslash;",
    "      outFile << *p;",
    "    }",
    "    outFile << quote << \",\" << nline;",
    "  }",
    "",
    "  for (i = bstart; i < bstop; ++i) {",
    "    outFile << text[i] << nline;",
    "  }",
    "",
    "  outFile.close();",
    "  return 0;",
    "}",
    "------------------- Python Code ------------------",
    "text = [",
    "]",
    "",
    "hstart = 107",
    "hstop  = 108",
    "bstart = 108",
    "bstop  = 140",
    "quote  = chr(042)",
    "nline  = chr(012)",
    "bslash = chr(0134)",
    "",
    "def main():",
    "    fo = open(\"rcopy.rb\", \"w\")",
    "    for x in range(hstart, hstop):",
    "        fo.write(text[x] + nline);",
    "    for line in text:",
    "        fo.write(\"   \" + quote);",
    "        fo.write(line.replace(quote, bslash + quote));",
    "        fo.write(quote + \",\" + nline);",
    "    for x in range(bstart, bstop):",
    "        fo.write(text[x] + nline);",
    "    fo.close()",
    "",
    "main()",
    "-------------------- Ruby Code -------------------",
    "$text = [",
    "];",
    "",
    "$quote = 34.chr;",
    "$bslash = 92.chr;",
    "$comma = \",\";",
    "$hstart = 141;",
    "$hstop = 146;",
    "$bstart = 147;",
    "$bstop = 182;",
    "",
    "def main();",
    "   fout = File.open(\"Jcopy.java\", \"w\");",
    "   for i in $hstart..$hstop",
    "      fout.puts $text[i]",
    "   end",
    "   for i in 0..($text.size - 1)",
    "      fout.print (\"      \" + $quote)",
    "      $text[i].each_char do|j|",
    "         if j == $quote",
    "            fout.print ($bslash)",
    "         end",
    "         fout.print (j)",
    "      end",
    "      fout.puts ($quote + $comma)",
    "   end",
    "   for i in $bstart..$bstop",
    "      fout.puts $text[i]",
    "   end",
    "   fout.close;",
    "end;",
    "",
    "main();",
    "-------------------- Java Code -------------------",
    "package quine;",
    "import java.io.*;",
    "",
    "public class Jfinal {",
    "  public static void main(String[] args) throws IOException {",
    "    String[] text = {",
    "    };",
    "    char quote = 042, nline = 012, bslash = 0134;",
    "    int hstart = 1, hstop = 6;",
    "    int bstart = 6, bstop = 41;",
    "    PrintWriter fout = null;",
    "",
    "    try {",
    "      fout = new PrintWriter(\"ccopy.c\");",
    "",
    "      for(int i = hstart; i < hstop; i++) {",
    "        fout.println(text[i]);",
    "      }",
    "",
    "      for(int i = 0; i < text.length; i++) {",
    "        fout.print(\"  \" + quote);",
    "        for (int j = 0; j < text[i].length(); j++) {",
    "          char c = text[i].charAt(j);",
    "          if (c == quote) {",
    "            fout.print(bslash);",
    "          }",
    "          fout.print(c);",
    "        }",
    "        fout.println(quote + \",\");",
    "      }",
    "",
    "      for(int i = bstart; i < bstop; i++) {",
    "        fout.println(text[i]);",
    "      }",
    "",
    "    } finally {",
    "      if (fout != null) {",
    "        fout.close();",
    "      }",
    "    }",
    "  }",
    "}",
  };

  char quote = 042, bslash = 0134, nline = 012;
  int i = 0, hstart = 82, hstop = 83;
  int bstart = 83, bstop = 106, maxLine = 183;
  const char* p;

  ofstream outFile("pcopy.py");

  for (i = hstart; i < hstop; ++i) {
    outFile << text[i] << nline;
  }

  for (i = 0; i < maxLine; ++i) {
    outFile << "    " << quote;
    for (p = text[i].c_str(); *p; ++p) {
      if (*p == quote)
        outFile << bslash;
      outFile << *p;
    }
    outFile << quote << "," << nline;
  }

  for (i = bstart; i < bstop; ++i) {
    outFile << text[i] << nline;
  }

  outFile.close();
  return 0;
}
