Proj2.out: Deck.o Card.o Player.o Hand.o Blackjack.o Proj2.cpp
	g++ -ansi -Wall Deck.o Card.o Player.o Hand.o Blackjack.o Proj2.cpp -o Proj2.out

Deck.o: Deck.cpp
	g++ -Wall -c Deck.cpp

Card.o: Card.cpp
	g++ -Wall -c Card.cpp

Player.o: Player.cpp
	g++ -Wall -c Player.cpp

Hand.o: Hand.cpp
	g++ -Wall -c Hand.cpp

Blackjack.o: Blackjack.cpp
	g++ -Wall -c Blackjack.cpp