CPPFLAGS = -Wall
OBJS = Proj2.o Card.o Deck.o Player.o Hand.o Blackjack.o

Proj2.out: ${OBJS}
	g++ ${OBJS} -o Proj2.out

Card.o: Card.h Card.cpp
Deck.o: Deck.h Deck.cpp
Hand.o: Hand.h Hand.cpp
Player.o: Player.h Player.cpp
Blackjack.o: Blackjack.h Blackjack.cpp
Proj2.o: Proj2.cpp